### ISSUE TITLE
Flexbar should not allow more barcode reads than reads to split

### ISSUE THREAD

**Issue by tzk** [seqan/flexbar#2]
Hi,

I would like to propose an additional check to guard agains errors during barcode detection: Flexbar should check if the number of barcode reads (--br) matches the number of reads.

When there are fewer barcode reads than regular reads, Flexbar exits with error  ("Processing reads ...Error: reads without barcode read or file reading error!"). In the reverse case, when there are more barcode reads than regular reads, Flexbar splits the reads and silently drops the remaining barcode reads. The most likely cause for having more barcode reads would be that some reads got lost. In this case the barcode reads and regular reads are out of sync and the split reads will all be jumbled.

Alternatively, it might be a nice feature to require the ids of barcode and regular reads to match. Not sure if this wouldn't be too stringent, though.

Best,
Daniel

**Comment by jtroehr** [comment]
Hi Daniel,

thank you a lot for the hint and comments. I will add the proposed check for barcode reads.

I also think that it might be too stringent to require the ids to match, because the number of different characters at the end of ids could vary. But perhaps it would be nice to have an option to enable such a check and specify this number. Will think about it.

Best,
Johannes

**Comment by jtroehr** [comment]
Added proposed tests for barcode reads to develop branch.
