### ISSUE TITLE
split reads including barcode rads while use `-br` option

### ISSUE THREAD

**Issue by kvshams** [seqan/flexbar#23]
I am trying to demultiplex using barcoded reads with `-br`. 
`flexbar -r 2_HMWWKBGXB.2.1.fastq.gz -p 2_HMWWKBGXB.2.2.fastq.gz -b barcodes.fasta -br 2_HMWWKBGXB.2.barcode_1.fastq.gz --zip-output GZ`
Current output only providing the read1 and read2 only not the barcode one. This would be a great for the single cell analysis especially to the 10x data format

thanks,
Shams

**Comment by jtroehr** [comment]
Thanks for your feature request. There is no option for this because the output file names of reads include the barcode name anyway - which can also be the barcode sequence. So I did not see a need for that. But that is not sufficient for your use case, right?

In that case I would consider to include an option for this in a future release.

Kind regards,
Johannes

**Comment by kvshams** [comment]
@jtroehr Thanks for your reply. The need for the barcode is for 10x based single cell analysis using ``` cellranger ``` . It would be really great to include this in the future release.

Thanks,
Shams

**Comment by jtroehr** [comment]
Ok, I will let you know as soon as this feature is available

Johannes

**Comment by jtroehr** [comment]
Dear Shams,

I implemented this feature and added an option: ``--barcode-reads-out``

You find the new Flexbar version in the develop branch of the repo:
https://github.com/seqan/flexbar/tree/develop

Please let me know if something does not work as expected.

Kind regards,
Johannes
